[2023-03-10T20:04:36.414+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag.create_emp_table manual__2023-03-10T20:04:35.142042+00:00 [queued]>
[2023-03-10T20:04:36.421+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag.create_emp_table manual__2023-03-10T20:04:35.142042+00:00 [queued]>
[2023-03-10T20:04:36.422+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-10T20:04:36.422+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-10T20:04:36.423+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-10T20:04:36.431+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): create_emp_table> on 2023-03-10 20:04:35.142042+00:00
[2023-03-10T20:04:36.435+0000] {standard_task_runner.py:55} INFO - Started process 3104 to run task
[2023-03-10T20:04:36.439+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snf_dag', 'create_emp_table', 'manual__2023-03-10T20:04:35.142042+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/snf_dag.py', '--cfg-path', '/tmp/tmp3lnylijp']
[2023-03-10T20:04:36.440+0000] {standard_task_runner.py:83} INFO - Job 20: Subtask create_emp_table
[2023-03-10T20:04:36.494+0000] {task_command.py:388} INFO - Running <TaskInstance: snf_dag.create_emp_table manual__2023-03-10T20:04:35.142042+00:00 [running]> on host 1e740946fd0d
[2023-03-10T20:04:36.543+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=snf_dag
AIRFLOW_CTX_TASK_ID=create_emp_table
AIRFLOW_CTX_EXECUTION_DATE=2023-03-10T20:04:35.142042+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-10T20:04:35.142042+00:00
[2023-03-10T20:04:36.544+0000] {sql.py:254} INFO - Executing: create_employee_table
[2023-03-10T20:04:36.562+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 255, in execute
    hook = self.get_db_hook()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 179, in get_db_hook
    return self._hook
  File "/home/airflow/.local/lib/python3.7/site-packages/cached_property.py", line 36, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/common/sql/operators/sql.py", line 141, in _hook
    conn = BaseHook.get_connection(self.conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/hooks/base.py", line 72, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/connection.py", line 435, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `snowflake_default` isn't defined
[2023-03-10T20:04:36.565+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=snf_dag, task_id=create_emp_table, execution_date=20230310T200435, start_date=20230310T200436, end_date=20230310T200436
[2023-03-10T20:04:36.573+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 20 for task create_emp_table (The conn_id `snowflake_default` isn't defined; 3104)
[2023-03-10T20:04:36.616+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-10T20:04:36.636+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
