[2023-03-10T20:01:59.644+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag.create_emp_table manual__2023-03-10T20:00:26.580507+00:00 [queued]>
[2023-03-10T20:01:59.649+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: snf_dag.create_emp_table manual__2023-03-10T20:00:26.580507+00:00 [queued]>
[2023-03-10T20:01:59.650+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-10T20:01:59.650+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 2
[2023-03-10T20:01:59.650+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-10T20:01:59.657+0000] {taskinstance.py:1300} INFO - Executing <Task(SnowflakeOperator): create_emp_table> on 2023-03-10 20:00:26.580507+00:00
[2023-03-10T20:01:59.662+0000] {standard_task_runner.py:55} INFO - Started process 2911 to run task
[2023-03-10T20:01:59.665+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'snf_dag', 'create_emp_table', 'manual__2023-03-10T20:00:26.580507+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/snf_dag.py', '--cfg-path', '/tmp/tmpqprkoawn']
[2023-03-10T20:01:59.666+0000] {standard_task_runner.py:83} INFO - Job 19: Subtask create_emp_table
[2023-03-10T20:01:59.717+0000] {task_command.py:388} INFO - Running <TaskInstance: snf_dag.create_emp_table manual__2023-03-10T20:00:26.580507+00:00 [running]> on host 1e740946fd0d
[2023-03-10T20:01:59.737+0000] {abstractoperator.py:613} ERROR - Exception rendering Jinja template for task 'create_emp_table', field 'sql'. Template: 'create_employee_table.sql'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_employee_table.sql
[2023-03-10T20:01:59.739+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1374, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1493, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 2115, in render_templates
    original_task.render_template_fields(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 1179, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 75, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 606, in _do_render_template_fields
    seen_oids,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/abstractoperator.py", line 657, in render_template
    template = jinja_env.get_template(value)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 1010, in get_template
    return self._load_template(name, globals)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/environment.py", line 969, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/home/airflow/.local/lib/python3.7/site-packages/jinja2/loaders.py", line 218, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: create_employee_table.sql
[2023-03-10T20:01:59.747+0000] {taskinstance.py:1323} INFO - Marking task as UP_FOR_RETRY. dag_id=snf_dag, task_id=create_emp_table, execution_date=20230310T200026, start_date=20230310T200159, end_date=20230310T200159
[2023-03-10T20:01:59.753+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 19 for task create_emp_table (create_employee_table.sql; 2911)
[2023-03-10T20:01:59.800+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-10T20:01:59.819+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
